spring:
  application:
    name: eureka-server-hw

server:
  port: 22222

eureka:
  client:
    register-with-eureka: false  # ?? Eureka ??? ? ??? ???? ??
    fetch-registry: false  # ?? Eureka ??? ?????? ???? ??
    service-url:
      default-zone: http://localhost:19090/eureka/
  server:
    enable-self-preservation: false  # ?? ?? ?? ????