spring:
  application:
    name: order-service-hw
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: Database
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:22222/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0